# Generated by Django 5.0.2 on 2024-02-09 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_clients_tag"),
        ("mailings", "0002_mailing_clients"),
        ("messages_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clients.clients",
            ),
        ),
        migrations.AddField(
            model_name="messages",
            name="mailings",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mailings.mailing",
            ),
        ),
    ]
