# Generated by Django 5.0.2 on 2024-02-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messages_app", "0002_messages_client_messages_mailings"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="errors",
            field=models.TextField(null=True),
        ),
    ]
