version: "3.10.12"

services:
  app:
    build:
      dockerfile: "./Dockerfile"
    command:
      - "gunicorn"
      - "notice_f.wsgi:application"
      - "--bind"
      - "0.0.0.0:8000"

    ports:
      - "8000:8000"
    restart: "always"
    env_file:
      - ".env"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      # изменить эту строку
      - "./mysite/database:/app/database"


