version: "3.10"

volumes:
  postgres_data:

services:
  app:
    build:
      context: .
      dockerfile: "./Dockerfile"
    container_name: "notice_django"
    command:
      - "gunicorn"
      - "notice_f.wsgi:application"
      - "--bind"
      - "0.0.0.0:8000"
      - "--access-logfile=-"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - "8000:8000"
    restart: "always"
    env_file:
      - ".env"
    depends_on:
      - db

  db:
    container_name: "postgres"
    image: postgres:latest
    env_file:
      - ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  redis:
    container_name: "redis"
    image: redis:latest
    depends_on:
      - db
      - app
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
    container_name: "celery_worker"
    image: celery:latest
    command:
      - "celery"
      - "-A"
      - "notice_f"
      - "worker"
      - "--loglevel=DEBUG"
    depends_on:
      - db
      - app
      - redis
    volumes:
      - ./:/app

  celery_beat:
    build:
      context: .
    container_name: "celery_beat"
    image: celery:latest
    command:
      - "celery"
      - "-A"
      - "notice_f"
      - "beat"
      - "--loglevel=DEBUG"
    depends_on:
      - db
      - app
      - celery_worker
      - redis
    volumes:
      - ./:/app
