# Generated by Django 5.0.2 on 2024-02-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=7, null=True)),
                (
                    "timezone",
                    models.CharField(
                        choices=[
                            ("Europe/Kaliningrad", "Europe/Kaliningrad"),
                            ("Europe/Moscow", "Europe/Moscow"),
                            ("Europe/Samara", "Europe/Samara"),
                            ("Asia/Yekaterinburg", "Asia/Yekaterinburg"),
                            ("Asia/Omsk", "Asia/Omsk"),
                            ("Asia/Krasnoyarsk", "Asia/Krasnoyarsk"),
                            ("Asia/Irkutsk", "Asia/Irkutsk"),
                            ("Asia/Yakutsk", "Asia/Yakutsk"),
                            ("Asia/Vladivostok", "Asia/Vladivostok"),
                            ("Asia/Magadan", "Asia/Magadan"),
                            ("Asia/Kamchatka", "Asia/Kamchatka"),
                        ],
                        null=True,
                    ),
                ),
                ("mobile_code", models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
