# Generated by Django 5.0.2 on 2024-02-09 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_clients_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="mobile_code",
            field=models.CharField(
                max_length=3,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.MaxLengthValidator(3),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="clients",
            name="phone",
            field=models.CharField(max_length=7, null=True, unique=True),
        ),
    ]
