# Generated by Django 5.0.2 on 2024-02-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("mailings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="clients",
            field=models.ManyToManyField(null=True, to="clients.clients"),
        ),
    ]
