# Generated by Django 5.0.2 on 2024-02-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_mailing_clients"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Открыт"),
                    ("working", "В работе"),
                    ("archived", "Архив"),
                ],
                default="open",
                max_length=10,
            ),
        ),
    ]
